### ISSUE TITLE
Documentation needed for private TF modules repositories

### ISSUE THREAD

**Issue by ArieLevs** [flux-iac/tofu-controller#1189]
Hi,

Its seem i'm missing the integration of tf-controller with private repo terraform modules,
my use case is i create a `GitRepository` resource that points to a git repo hosting tf code, the source controller picks it up and all is OK.
Then i deploy a `Terraform` resource that points to a directory path with TF code, 
part of that code i use a private source module, that looks like:
```
module "vpc" {
  source  = "my.private.server/terraform-modules/path/to/module"
  version = "1.2.3"
  
  ...
  ...
}
```
flux runner returns:
```
Error: Error accessing remote module registry

Failed to retrieve available versions for module "vpc" (main.tf:5) from
my.private.server: error looking up module versions: 401 Unauthorized.


Error: Error accessing remote module registry

Failed to retrieve available versions for module "vpc" (main.tf:5) from
my.private.server: error looking up module versions: 401 Unauthorized.
```

if i `terraform apply` from my local env, then i obviously need to first execute `terraform login my.private.server`,
but what would be the equivalent for `kind: Terraform` ?

**Comment by ArieLevs** [comment]
Hi @chanwit @yitsushi 
Could you please assist here, is the above scenario supported (or will be in new tofu controller) ?
the lack of support working with private submodules is real blocker for me.
thanks

**Comment by chanwit** [comment]
We support mostly anything that Terraform can do. 

Please check to see how would you specificy this kind of credentials without non-interactively, then you would see a kind of file you needed to do so.

We support specifying Terraform Cloud credentials with .tfrc file for example.

**Comment by ilithanos** [comment]
For pulling modules and providers from private registries that requires authentication the credentials needs to be configured in the tf configuration file:

https://developer.hashicorp.com/terraform/cli/config/config-file#credentials

This is done in the .tfrc file.

This can be provided to the runner in multiple ways.

Documenting this sounds like a good idea though, and might be a good first issue for someone wanting to contribute to the project.

**Comment by ArieLevs** [comment]
Thanks using native Terraform login process totally solved the issue!

I've created #1237 with basic examples for the above use case, please let me know if this aligns with the project's standards
