### ISSUE TITLE
Replace all occurrences of tf-controller

### ISSUE THREAD

**Issue by akselleirv** [flux-iac/tofu-controller#1208]
The repository still contains a fair bit of references to the old tf-controller name. Should all these references be changed?

**Comment by chanwit** [comment]
yes, of course. 
Please refer to https://github.com/flux-iac/tofu-controller/issues/1200 where there are some sub-issues going on.

**Comment by akselleirv** [comment]
Okay, did not know of that issue. I'll close this one and keep the discussion there.
