### ISSUE TITLE
Better CRDs handling

### ISSUE THREAD

**Issue by sirloon** [flux-iac/tofu-controller#1209]
I had an issue while upgrading the TF controller this morning. It’s deployed using **Terraform**.

The current way tf-controller helm chart is using to install CRDs is using a template file, [located](https://github.com/flux-iac/tofu-controller/blob/a56c128f070eff1d8252b36fdb1590f34ffad298/charts/tf-controller/templates/crds.yaml) in the `templates` folder. This can cause issue when uninstalling the chart: the CRDs gets deleted, which in turn can trigger a "terraform destroy" on the corresponding CR. I have observed this behavior upgrading from tf-controller to tofu-controller. My Terraform CR got deleted and underlying resources destroyed. The CRD status turned into "Terminating", waiting for the finalizer to finish destroying resources, as seen in this k9s screenshot (note I rolled back to previous tf-controller version before the end of CR termination)

![image](https://github.com/flux-iac/tofu-controller/assets/2883770/5b3f3e36-d2c7-4d59-bfca-666e4e71ec7e)

According to Helm [documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations), the standard way to deploy CRDs on a cluster is to locate them in a `crds` folder. By design, `helm uninstall ...` won't touch the CRDs defined there, so it's safer to upgrade the controller in case, for whatever reason, it's required to uninstall and reinstall it. In current deployment, CRDs are just uninstalled from k8s, just like any other "normal" objects.

**Comment by ilithanos** [comment]
This one actually seems critical to me. As not fixing this could result in users production environments going down in a worst case scenario.

If no one picks this up, I'll take a look at it when I'm done with the organisation fixes for the rest of the repo.

**Comment by seb-inf** [comment]
We use `destroyResourcesOnDeletion` option to prevent this kind of situations. It has cons like you need to enable it before actual deleting resources

**Comment by dgem** [comment]
From [docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you), in addition to previously mentioned by @sirloon :

> ... There is now a special directory called crds that you can create in your chart to hold your CRDs. **These CRDs are not templated**, but will be installed by default when running a helm install for the chart.

The main use of templates seems to be at https://github.com/flux-iac/tofu-controller/blob/main/charts/tf-controller/templates/crds.yaml#L10 for `labels`. Presumable a set of static labels based on the [current helpers](https://github.com/flux-iac/tofu-controller/blob/main/charts/tf-controller/templates/_helpers.tpl#L33):
```
{{/*
Common labels
*/}}
{{- define "tf-controller.labels" -}}
helm.sh/chart: {{ include "tf-controller.chart" . }}
{{ include "tf-controller.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
control-plane: controller
{{- end }}
```

**Comment by ilithanos** [comment]
I don't think we will be able to get around a delete as it is currently. 

My suggestion given the current state of things would be to update the chart to where it won't create the issue again.

Then write a migration guide that should come out together with the next release in how to migrate as painless as possible.
