### ISSUE TITLE
Update Alpine in base image to make it pass the CVE scanner

### ISSUE THREAD

**Issue by chanwit** [flux-iac/tofu-controller#1219]
We currently use a quite outdated version of Alpine. That's why we got many CVEs in OS packages. 

https://github.com/flux-iac/tofu-controller/blob/main/runner-base.Dockerfile#L41

The version of Alpine needs to be updated so that we get new enough OS packages to avoid CVEs.

**Comment by ilithanos** [comment]
https://peps.python.org/pep-0668/

This seems to be creating an issue when updating alpine for the azure runners. The way pip is updated and the azure cli is installed conflicts with that.

two options:

The quick solution is adding --break-system-packages to the commands, bypassing the virtual environment requirement.

The other solution is to setup a virtual env and install the cli into that.

Running local e2e tests with the quick solution currently to see how it goes.
