### ISSUE TITLE
Security Reporting document needs updating

### ISSUE THREAD

**Issue by ilithanos** [flux-iac/tofu-controller#1222]
The security document still refers to weaveworks emails and descriptions for reporting security issues. A new reporting procedure should be set up and documented.

Not sure how this will be handled now that it's a community project, but a decision must be made on this at some point.

**Comment by dgem** [comment]
There is a [private security vuln reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability) feature, which avoid needing an email...

**Comment by ilithanos** [comment]
Sounds like the way to go @dgem, but it's something either @chanwit or someone else with maintainer status has to set up i guess. I mainly created the issue so that it didn't get missed in the rush to get everything else fixed up.

**Comment by chanwit** [comment]
Agreed that we would of course remove the email and go with the GitHub option instead.

Thank you both @ilithanos @dgem

**Comment by chanwit** [comment]
fixed by de9999b2bd7dc336893d89152573c025e9d6908a
