### ISSUE TITLE
Speed up binary building in Tilt

### ISSUE THREAD

**Issue by akselleirv** [flux-iac/tofu-controller#1225]
Currently the binaries are built with Docker when using Tilt, but if it was moved to the local machine using `local_resource` then it can utilize the native go caching which would speed up the builds drastically.

Implementation options:

1) Either create a separate Dockerfile for all the builds (manager, tf-runner and branch-planner) which would result in some code duplication.
2) Build the binary outside of the Dockerfile and only copy the binary. This would mean that the GitHub workflow must run `go build` instead of doing it in the Dockerfile.

**Comment by ilithanos** [comment]
Not sure if I like the idea of moving it out of the Docker file as it might introduce inconsistent results based on the build environment and runtime environments.

The there is already a seperate Docker file for runners with a base image where platform specific addons are added in a seperate Docker file for that.

Could a similar solution be an option so that the base didn't have to be rebuild every time, and at the same time keep the containerization benefits?

**Comment by akselleirv** [comment]
> Not sure if I like the idea of moving it out of the Docker file as it might introduce inconsistent results based on the build environment and runtime environments.
I definlity see your argument here.

> The there is already a seperate Docker file for runners with a base image where platform specific addons are added in a seperate Docker file for that.

Yes, but then I would also need to create similar Dockerfiles for the other builds (options 1). The only downside there is some duplication of code between the main Dockerfile and a Dockerfile.dev.

For example for the manager it would be:

Dockerfile.dev
```
# The building of the manager is removed. 
FROM alpine:3.19

LABEL org.opencontainers.image.source="https://github.com/flux-iac/tofu-controller"

ARG LIBCRYPTO_VERSION

RUN apk update && \
    apk add --no-cache \
    libcrypto3=${LIBCRYPTO_VERSION} \
    libssl3=${LIBCRYPTO_VERSION} \
    ca-certificates tini git openssh-client gnupg \
    libretls \
    busybox


COPY bin/tofu-controller /usr/local/bin/   <------------ The only change required

RUN addgroup --gid 65532 -S controller && adduser --uid 65532 -S controller -G controller

USER 65532:65532

ENV GNUPGHOME=/tmp

ENTRYPOINT [ "/sbin/tini", "--", "tofu-controller" ]
```

**Comment by ilithanos** [comment]
I don't think we will be able to get completely DRY anyway. 

But speeding up build times is a good thing if it's not at to high a cost on readability and consistency.

I think going with a base and specific builds on top of that might be the way to go. 

I'm no expert on tilt though which is also why I haven't taken than one up myself yet, so I'm not highly opinionated when it comes to that specific tool.

My suggestion would be to see if it can be done as multiple stages by utilizing a combination of base container images and maybe even multi stage builds to utilize the Docker build caching system?
