### ISSUE TITLE
Update DEVELOPMENT.md with Tilt setup

### ISSUE THREAD

**Issue by akselleirv** [flux-iac/tofu-controller#1236]
The current local [development section](https://github.com/flux-iac/tofu-controller/blob/main/DEVELOPMENT.md#how-to-run-the-controller-locally) in the DEVELOPMENT.md does not mentioned how to run the project using Tilt.

Should we consider replacing the current section entirely with Tilt? It offers a much simpler approach to running it locally.

The Tilt setup only requires two commands:
```
# Start kind with local registry
./tools/reboot.sh 

# Compile and deploy
tilt up
```

**Comment by ilithanos** [comment]
Sounds like a good idea to me, the current tooling described in the .md actually doesn't work on my intel Mac, so updating that tooling is pretty high on my to-do list.

I'll test the Tilt tooling together with the open PR for speeding up builds. If that works as it should I think this will be the way to go for development setups.

If we go this way I think we should consider updating the makefile to also use tilt for dev related make targets.
