### ISSUE TITLE
Unable to see `v0.16.0-rc.3` in releases for tofu

### ISSUE THREAD

**Issue by mkazla** [flux-iac/tofu-controller#1249]
When trying to download Docker image from `tofu-controller` for `v0.16.0-rc.3` it says 

```
$ docker pull ghcr.io/flux-iac/tofu-controller:v0.16.0-rc.3
Error response from daemon: manifest unknown
```

Kindly help me in getting the correct docker image, in searching it does not show me the version I want in packages. 

Thanks

**Comment by chanwit** [comment]
Hi @mkazla 
unfortunately, v0.16.0-rc.3 was from the Weavework repo.

But we have just released v0.16.0-rc.4.
