### ISSUE TITLE
Helm template fails for v0.16.0-rc.4 when you specify imagePullSecrets

### ISSUE THREAD

**Issue by ayanevbg** [flux-iac/tofu-controller#1250]
When you specify custom **imagePullSecrets** the chart fails to render.

This is because a secret was added in **runner-serviceaccount.yaml** but the end block for the **{{- with $.Values.imagePullSecrets }}** statement is after the Secret.

Should be easy fix by moving one of the {{- end }} af the end of the file to line 18.

imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}

**Comment by ayanevbg** [comment]
It seems that the same version is pushed for chart v0.16.0-rc.3. Although the code for this version says otherwise - https://github.com/flux-iac/tofu-controller/blob/v0.16.0-rc.3/charts/tf-controller/templates/runner-serviceaccount.yaml

**Comment by chanwit** [comment]
Thank you @ayanevbg would you mind put up an PR for it so I could help review this quickly?

**Comment by ayanevbg** [comment]
Thank you @chanwit . I put up an PR - https://github.com/flux-iac/tofu-controller/pull/1251

**Comment by chanwit** [comment]
Fantastic!!
Thank you so much for the PR.

Will cut RC.5 to address this issue today.
