### ISSUE TITLE
storeReadablePlan Plan read error

### ISSUE THREAD

**Issue by hirenko-v** [flux-iac/tofu-controller#1262]
Hello! 
I have such a manifest
```
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: example
  namespace: flux-system
spec:
  alwaysCleanupRunnerPod: true
  backendConfig:
    disable: true
  destroyResourcesOnDeletion: false
  disableDriftDetection: false
  force: false
  interval: 1m
  parallelism: 0
  path: ./terraform/example
  refreshBeforeApply: false
  runnerTerminationGracePeriodSeconds: 30
  serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  storeReadablePlan: json
```

TF controller version is v0.16.0-rc.2 (or .3)

I am getting the error 

```
  Warning  TFExecPlanFailed  5s  tf-controller  error saving plan secret: rpc error: code = Unknown desc = 
Error: Failed to read the given file as a state or plan file

State read error: Error loading statefile: open tfplan: no such file or
directory

Plan read error: open tfplan: no such file or directory
```

Seems like it is connected to storeReadablePlan because when I set it to none it works like a charm

**Comment by chanwit** [comment]
```
  backendConfig:
    disable: true
```

This would cause your problem.
`backend.disable` has been designed to use with Terraform Cloud where planning happens on the SaaS so no plan generated locally. And it means to completely disable any Terraform backends and use only Terraform Cloud connections.

So please set it back to true as you actually have backendConfig somewhere in your TF codes.
And provide an empty customBackend block of your backend for the Terraform object to run correctly.

We have an issue to track the semantic change of this bad design here: https://github.com/flux-iac/tofu-controller/issues/1238

**Comment by hirenko-v** [comment]
Just posted the workaround there:
https://github.com/flux-iac/tofu-controller/issues/1238#issuecomment-2011646427
