### ISSUE TITLE
infra.contrib.fluxcd.io/v1alpha2\": Not Implemented"

### ISSUE THREAD

**Issue by yoyoraso** [flux-iac/tofu-controller#1265]
Hello, I am trying to install the controller in network isolated cluster and added proxy throw env var HTTPS_PROXY but it seems that there is an error keeps crashing the controller container {"level":"error","ts":"2024-03-24T19:11:34.324Z","logger":"setup","msg":"unable to create controller","controller":"Terraform","error":"failed setting index fields: failed to get API group resources: unable to retrieve the complete list of server APIs: infra.contrib.fluxcd.io/v1alpha2: Get \"https://IP:443/apis/infra.contrib.fluxcd.io/v1alpha2\": Not Implemented"}
at first I saw that crd infra.contrib.fluxcd.io wasn't installed so I installed it throw yaml file I had from another open cluster but same error kept showing. 
I also gave role/clusterrole wide permission but error stay same so now I am stuck on debugging the error.

**Comment by chanwit** [comment]
It's clearly that the installation process failed somewhere during the installation of CRDs.

May I know how did you install the controller?

**Comment by yoyoraso** [comment]
> It's clearly that the installation process failed somewhere during the installation of CRDs.
> 
> May I know how did you install the controller?

I downloaded images from public registry and repushed it to privet one then made template for the helm chat changing the image  also did the same with the OCIRepository
