### ISSUE TITLE
Branch planner does not comment of PR if plan failed due to post plan web hook 

### ISSUE THREAD

**Issue by raz-bn** [flux-iac/tofu-controller#1270]
If post plan web hook is configured and plan failed because of it the Branch Planner does not post a comment on the PR. 

possibly here is the reason:
https://github.com/flux-iac/tofu-controller/blob/786da834e38521155af4d2ea34e285cd63ff24e3/internal/informer/branch-planner/informer.go#L152

**Comment by chanwit** [comment]
Thank you for the PR @raz-bn 
Will take a look at it shortly.
