### ISSUE TITLE
Helm chart 0.16.0-rc.4 issue with runner-discovery-service.yaml

### ISSUE THREAD

**Issue by DanielAntos90** [flux-iac/tofu-controller#1280]
Hi,

I was trying to use latest helm chart from main branch and I get this error in flux cd.

Helm install failed for release flux-system/tf-controller with chart tofu-controller@0.16.0-rc.4: template: tofu-controller/templates/runner-discovery-service.yaml:2:10: executing "tofu-controller/templates/runner-discovery-service.yaml" at <include "tf-controller.runner.allowedNamespaces" .>: error calling include: template: no template "tf-controller.runner.allowedNamespaces" associated with template "gotpl"

**Comment by ilithanos** [comment]
Thanks for reporting this.

I'll see if i can see exactly whats going on with the chart.

Looks like you are using the new chart that was renamed to tofu-controller right?

**Comment by DanielAntos90** [comment]
Thats right. I am using the latest version in main branch.
