### ISSUE TITLE
"https://weaveworks.github.io/tf-controller" is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by ypereirareis** [flux-iac/tofu-controller#1289]
Hello.

Since a few days we are having this error regarding `tf-controller` in our stacks.

```
failed to fetch https://weaveworks.github.io/tf-controller/index.yaml : 404 Not Found :
unable to run: 'helm pull --untar --untardir <path to cached source>/operators/tf-controller/charts
--repo https://weaveworks.github.io/tf-controller tf-controller --version 0.11.0' 
```

Please can you tell us how to properly migrate to the new helm chart repo and 0.11.0 version ?

Thanks a lot.

**Comment by ilithanos** [comment]
As @kingdonb mentioned the weaveworks chart repo doesn't exist any more, and you need to use the flux-iac repo instead. Try following the instructions in the above link, and see if it fixes the issue. 0.11.0 is a very old version though, and it might be time to update to a newer version of the chart and controller.

**Comment by ilithanos** [comment]
Closing this, at it's not an issue with the current version but an old issue with using the old weaveworks repos instead of the flux-iac repo
